version: '3.8'

services:
  mysql:
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camunda_db
    networks:
      - workflow-network

  camunda:
    image: thaiduy0282/workflow-camunda-engine:latest
    container_name: camunda
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/camunda_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      WORKFLOW_SERVICE_URL: http://workflow:8090
      ADMIN_USER: demo
      ADMIN_PASSWORD: demo
    networks:
      - workflow-network

  akka-message:
    image: thaiduy0282/akka-message:latest
    container_name: akka-message
    ports:
      - "8085:8085"
      - "8888:8888"
    environment:
      TCP_PORT: 8888
      HTTP_PORT: 8085
      TCP_SERVER_ADDRESS: "akka-message"
    networks:
      - workflow-network

  myapp:
    image: thaiduy0282/workflow-api:latest
    container_name: workflow
    ports:
      - "8090:8090"
    depends_on:
      - camunda
      - akka-message
    environment:
      SERVER_PORT: 8090
      AZURE_COSMOS_URI: https://qworks-workflow.documents.azure.com:443
      AZURE_COSMOS_KEY: AZURE_COSMOS_KEY
      AZURE_COSMOS_DATABASE: workflow_management
      CAMUNDA_BPM_CLIENT_BASE_URL: http://camunda:8080/engine-rest
      QWORKS_BASE_URL: https://dev.qworks.ai/metabench/api/
      TCP_SERVER_ADDRESS: akka-message
      TCP_PORT: 8888
    networks:
      - workflow-network

networks:
  workflow-network:
    driver: bridge
