spring:
  application:
    name: workflow
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      username: ${SPRING_DATA_MONGODB_USERNAME:admin}
      password: ${SPRING_DATA_MONGODB_PASSWORD:secret}
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:workflow_management}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

server:
  port: ${SERVER_PORT:8090}

camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
    autoDeploy:
      enabled: false

tcp:
  server:
    address: ${TCP_SERVER_ADDRESS:localhost}
    port: ${TCP_PORT:8888}

qworks:
  baseUrl: https://dev.qworks.ai/metabench/api/
